# Generated by Django 5.0.4 on 2024-04-10 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat', models.DateField(default='2000-1-1', verbose_name='تاريخ الحجز')),
                ('tim', models.TimeField(default='12:00:00', verbose_name='وقت الحجز')),
                ('num_of_hour', models.IntegerField(verbose_name='المدة')),
                ('phone', models.CharField(default='+963 900 000 000', max_length=100, verbose_name='موبايل')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
