# Generated by Django 5.0.4 on 2024-04-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='accsepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_of_hour',
            field=models.CharField(max_length=2, verbose_name='المدة'),
        ),
    ]
