# Generated by Django 5.0.4 on 2024-04-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_accsepted_alter_book_num_of_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reson',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='book',
            name='accsepted',
            field=models.CharField(blank=True, choices=[('accsepted', 'قبول'), ('rejected', 'رفض')], max_length=50, null=True, verbose_name='قبول الحجز'),
        ),
    ]
