# Generated by Django 5.0.4 on 2024-04-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_reson_alter_book_accsepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='accsepted',
            field=models.CharField(blank=True, choices=[('accsepted', 'قبول'), ('rejected', 'رفض'), ('hold', 'بانتظار')], default='بانتظار', max_length=50, null=True, verbose_name='قبول الحجز'),
        ),
    ]
