# Generated by Django 5.0.4 on 2024-04-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_book_accsepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dat',
            field=models.DateField(verbose_name='تاريخ الحجز'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tim',
            field=models.TimeField(verbose_name='وقت الحجز'),
        ),
    ]
