# Generated by Django 5.0.4 on 2024-04-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_book_dat_alter_book_tim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_of_hour',
            field=models.CharField(default='أدخل رقم الحجز، ساعتين على الأقل', max_length=2, verbose_name='المدة'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reson',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات من الأدمن'),
        ),
    ]
